// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class StoreOnlyDocuments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoreOnlyDocuments));
        
        string IMigrationMetadata.Id
        {
            get { return "201502062044437_StoreOnlyDocuments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
